#ifndef AMULETCORE_GLOBAL_HPP
#define AMULETCORE_GLOBAL_HPP

#include <QtCore/qglobal.h>

#if defined(AMULETCORE_LIBRARY)
#  define AMULETCORESHARED_EXPORT Q_DECL_EXPORT
#else
#  define AMULETCORESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // AMULETCORE_GLOBAL_HPP
